name: travo_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.3+2
  image_picker: ^0.8.7
  audio_waveforms: ^1.0.3
  path_provider: ^2.0.11
  file_picker: ^5.0.0
  image: ^4.0.15


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#  fonts:
#    - family: Comfortaa
#      fonts:
#        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
#          weight: 300
#        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
#          weight: 700
